config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  devise_scope :user do
    get "users/sign_out", to: "devise/sessions#destroy"
  end  
  resources :users, only: [:show] 
  resources :stories do
    resources :memberships, only: [:new, :create]
    resources :invites
    resources :lines, only: [:index]
  end
  post 'notifications/notify' => 'notifications#notify'
  post 'twilio/voice' => 'twilio#voice'
  post 'notifications/start' => 'notifications#start'

  post "sms", to: "notifications#process_sms" 
  

      
  
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :phone, presence: true
  validates :email, presence: true

  has_many :stories, :foreign_key => :creator_id, :through => :memberships
  has_many :memberships
  has_many :invitations, :class_name => "Invite", :foreign_key => 'recipient_id'
  has_many :sent_invites, :class_name => "Invite", :foreign_key => 'sender_id'
  has_many :lines

  def self.search(search)
    where("email like ?", "%#{search}%")    
  end
end

app/controllers/users_controller.rb
class UsersController <ApplicationController
  before_filter :authenticate_user!
  
  def index
    @users = User.all
  end

  def show
    @stories = current_user.stories.all
  end
end

app/views/users/show.html.erb
<div class = "titlepage">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class ="shelf-name">
        <h1><%= current_user.first_name %>'s Shelf</h1>
      </div>  
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <table class="table">
      <tbody>
        <tr>
          <% @stories.each do |story| %>
            <td><%= link_to story.title, story_path(story) %></td>
       </tr>
          <% end %>
      </tbody>
      </table>
    </div>
  </div>

  <button type="button" class="btn"><%= link_to "start a new story", new_story_path(current_user) %></button>
</div>