config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  devise_scope :user do
    get "users/sign_out", to: "devise/sessions#destroy"
  end  
  resources :users, only: [:show] 
  resources :stories do
    resources :memberships, only: [:new, :create]
    resources :invites
    resources :lines, only: [:index]
  end
  post 'notifications/notify' => 'notifications#notify'
  post 'twilio/voice' => 'twilio#voice'
  post 'notifications/start' => 'notifications#start'

  post "sms", to: "notifications#process_sms" 
  

      
  
  

  

end

app/models/story.rb
class Story < ActiveRecord::Base
  validates :title, presence: true
  validates :first_line, presence: true 
  belongs_to :creator, :class_name => "User"
  has_many :users, :through => :memberships
  has_many :memberships
  has_many :invites
  has_many :lines
end

app/controllers/stories_controller.rb
class StoriesController <ApplicationController
  before_filter :authenticate_user!

  def new
    @story = Story.new
    @creator = current_user
  end
    
  def create
    @story = Story.new(story_params)
    @story.creator_id = current_user.id
    @story.users << current_user   
    if @story.save
      flash[:notice] = "off to a great start!"
      redirect_to story_path(@story)
    else
      flash[:alert] = "some information was missing. try again."
      render :new
    end
  end

  def show
    @story = Story.find_by_id(params[:id])
    @users = @story.users.all
    @memberships = Membership.find_by_story_id(@story.id)
  end

  def destroy
    @story = Story.find_by_id(params[:id])
    @membership = Membership.find_by_story_id(@story)
    @story.destroy
    @membership.destroy
    flash[:notice] = "Story was deleted."
    redirect_to user_path(current_user)
  end


end



private

def story_params
  params.require(:story).permit(:title, :description, :first_line)
end

app/views/stories/_join.html.erb
<%= form_for(current_user.invites.build(joined_story_id: @story.id)) do |f| %>
  <div><%= f.hidden_field :joined_story_id %></div>
  <%= f.submit "Join", class: "btn" %>
<% end %>

app/views/stories/edit.html.erb
<%=form_for @invite, :url => invites_path do |f| %>
    <%= f.hidden_field :story_id, :value => @invite.story_id %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.submit 'Send' %>
<% end %>

app/views/stories/new.html.erb
<div class = "titlepage">
<h2>start a story</h2>

  <%=form_for @story, url: {action: "create"} do |f| %>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :description %><i> (optional)</i><br />
      <%= f.text_field :description %>
    </div>

    <div class="field">
      <%= f.label :first_line %><br />
      <%= f.text_area :first_line %>
    </div>

    <div class="actions">
      <%= f.submit "create story" %>
    </div>
  <% end %>
</div>

app/views/stories/show.html.erb
<div class="titlepage">
  <div class = "title">
    <h2><%= @story.title %></h2>
  </div>
  <p>written by</p>

    <div class="authors">
        <% @users.each do |user| %>
        <li><%= user.first_name %></li>
        <% end %>
    </div>

    <br><br>
    <div class="info">
      <p><b>Lines written: </b>
          <% if @story.lines.count == 0 %>
          <%= "1" %>
          <% else %>
          <%= @story.lines.count + 1 %>
          <% end %>
      </p>
      <% if @story.description.presence %>
        <p><b>Description: </b><%= @story.description %></p>
      <% end %>
      <p> <% if current_user.id == @story.creator_id %>
          <b>First line: </b><%= @story.first_line %>
          <% end %>
      </p>
    </div>

    <br><br>
    <div class = "row">
      <div class = "col-md-12 col-centered">
        <button type="button" class="btn"><%= link_to "add writers", new_story_invite_path(@story) %></button>
        <% if current_user.id == @story.creator_id %>
        <button type="button" class="btn"><%= link_to "start the circle", notifications_start_path(story_id: @story.id), method: :post, remote: true %></button>
        <% end %>
        <button type="button" class="btn"><%= link_to "full story", story_lines_path(@story), data: {confirm: "Are you sure the story is done?"} %></button>
        <% if current_user.id == @story.creator_id %>
          <button type="button" class="btn"><%= link_to "delete story", [@story, @membership], method: :delete, data: {confirm: "Are you sure you would like to delete this story?"} %></button>
        <% end %>
      </div>
    </div>
</div>

  